enum WalletType { bank, cash, e_wallet, investment, other }

extension WalletTypeExtension on WalletType {
  String get toSnakeCase {
    switch (this) {
      case WalletType.bank:
        return 'bank';
      case WalletType.cash:
        return 'cash';
      case WalletType.e_wallet:
        return 'e_wallet';
      case WalletType.investment:
        return 'investment';
      case WalletType.other:
        return 'other';
    }
  }

  String get displayName {
    switch (this) {
      case WalletType.bank:
        return 'Bank';
      case WalletType.cash:
        return 'Tunai';
      case WalletType.e_wallet:
        return 'E-Wallet';
      case WalletType.investment:
        return 'Investasi';
      case WalletType.other:
        return 'Lainnya';
    }
  }
}

extension StringExtension on String {
  WalletType get toWalletType {
    switch (this) {
      case 'bank':
        return WalletType.bank;
      case 'cash':
        return WalletType.cash;
      case 'e_wallet':
        return WalletType.e_wallet;
      case 'investment':
        return WalletType.investment;
      case 'other':
        return WalletType.other;
      default:
        return WalletType.other;
    }
  }
}

class Wallet {
  final String id;
  final String userId;
  final String name;
  final double initialBalance;
  final WalletType type;
  final bool isActive;
  final DateTime? createdAt;

  Wallet({
    required this.id,
    required this.userId,
    required this.name,
    required this.initialBalance,
    required this.type,
    required this.isActive,
    this.createdAt,
  });

  Map<String, dynamic> toJson() {
    return {
      // 'id': id, // Usually generated by DB on insert, but needed for update
      'user_id': userId,
      'name': name,
      'initial_balance': initialBalance,
      'type': type.toSnakeCase,
      'is_active': isActive,
      // 'created_at': createdAt?.toIso8601String(), // Managed by DB
    };
  }

  factory Wallet.fromJson(Map<String, dynamic> json) {
    return Wallet(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      name: json['name'] as String,
      initialBalance: (json['initial_balance'] as num).toDouble(),
      type: (json['type'] as String).toWalletType,
      isActive: json['is_active'] as bool,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : null,
    );
  }
}
